### ISSUE TITLE
How to set input_dim to be 2 or more?

### ISSUE THREAD

**Issue by lixus7** [LeiBAI/AGCRN#6]

**Comment by lixus7** [comment]
when i use your model into my task, it occurred error as follows:

    result = self.forward(*input, **kwargs)
  File "/home/cseadmin/yd/subway_out/AGCRN.py", line 114, in forward
    output, _ = self.encoder(source, init_state, self.node_embeddings)      #B, T, N, hidden
  File "/home/cseadmin/anaconda3/envs/torch1.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/cseadmin/yd/subway_out/AGCRN.py", line 66, in forward
    assert x.shape[2] == self.node_num and x.shape[3] == self.input_dim
AssertionError

Maybe because AGCRN did not support multiple input features?

**Comment by LeiBAI** [comment]
Hi lixus7,

AGCRN does support multiple input features.
Regarding your error, I think you should first update the config file (e.g., PEMSD4_AGCRN.conf) to set input_dim=2.
Please check the code throughtly.

Regards

Lei

**Comment by lixus7** [comment]
Thank you, I have found that it was because of my wrong dimension order of my dataset. Thank you again.
Appreciate for your kindness!
