### ISSUE TITLE
The data scale in trainer isn't consistent

### ISSUE THREAD

**Issue by Factos001** [LeiBAI/AGCRN#7]
Hi,

I found that in BasicTrainer.py, the scale of the model's outputs and labels isn't consistent when setting args.real_value=True. You may need to inverse transform the model's outputs to make it right.

**Comment by jiangxinke** [comment]
Yeap, I also found this, you will find AGCRN model's label's scaler is really high while the output's is smaller. He forgets to inverse transform.

>

**Comment by jiangxinke** [comment]
> Hi,
> 
> I found that in BasicTrainer.py, the scale of the model's outputs and labels isn't consistent when setting args.real_value=True. You may need to inverse transform the model's outputs to make it right.

**Comment by jiangxinke** [comment]
> Hi,
> 
> I found that in BasicTrainer.py, the scale of the model's outputs and labels isn't consistent when setting args.real_value=True. You may need to inverse transform the model's outputs to make it right.

Yeap, I also found this, you will find AGCRN model's label's scaler is really high while the output's is smaller. He forgets to inverse transform.

**Comment by jiangxinke** [comment]
> 

I still wonder why so many papers in Spatio-Temp's mae and rmse are all the same scaler !!!  They use the real data to compare with the normalize data and got this answer, wtf??

**Comment by LeiBAI** [comment]
> Hi,
> 
> I found that in BasicTrainer.py, the scale of the model's outputs and labels isn't consistent when setting args.real_value=True. You may need to inverse transform the model's outputs to make it right.

Thanks for the comment. When setting args.real_value=True, the output is the real value, not the normalized value. The corresponding codes are Line 47, 74, and 182 in BasicTrainer.py.
