### ISSUE TITLE
About the adjacency matrix in the code

### ISSUE THREAD

**Issue by RowanLiu97** [LeiBAI/AGCRN#9]
I read the code carefully and wanted to run it on other datasets. But I didn't find any code for adjacency matrix. Could you indicate where the adjacency matrix data is introduced in this code? Thanks!

**Comment by LeiBAI** [comment]
Thanks. There is no pre-computed adjacent matrix in AGCRN. We learn a soft adjacent matrix from the data automatically. You may check the paper and code again about it.
